modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Caelus/issues"
logoFile="caelus_icon.png"
logoBlur=false
[[mods]]
modId="caelus"
version="${version}"
displayName="Caelus API"
displayURL="https://github.com/TheIllusiveC4/CherishedWorlds"
authors="C4"
description='''
A coremod and API to provide developers access to elytra flight mechanics through an entity attribute.
'''
[[dependencies.caelus]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.caelus]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"