modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheIllusiveC4/Caelus/issues"
logoFile="caelus_icon.png"
[[mods]]
modId="caelus"
version="${file.jarVersion}"
displayName="Caelus API"
displayURL="https://minecraft.curseforge.com/projects/caelus"
authors="C4"
description='''
A coremod and API to provide developers access to elytra flight mechanics through an entity attribute.
'''
[[dependencies.caelus]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.caelus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,1.14)"
    ordering="NONE"
    side="BOTH"